name: synchuman
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pytorch=2.1.1
  - torchvision=0.16.1
  - torchaudio=2.1.1
  - pytorch-cuda=12.1
  - pip
  - pip:
      - accelerate
      - safetensors==0.4.5
      - diffusers==0.29.1
      - transformers==4.36.0
      - huggingface_hub
      - xformers==0.0.23.post1
